/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./screens/**/*.{js,jsx,ts,tsx}",
    "./pages/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "custom-green-1": "#14B8A6",
        "custom-green-2": "#0D9485",
        "custom-blue-1": "#F1F5F9",
        "custom-white-1": "#F2F2F2",
        "custom-white-2": "#CECECE",
        "custom-black-1": "#23272E",
        "custom-error-1": "#fae8e8",
        "custom-error-2": "#de5757",
        "custom-success-1": "#ebf5ec",
        "custom-success-2": "#47a855",
        "custom-warning-1": "#fcf3eb",
        "custom-warning-2": "#e89241",
        "custom-info-1": "#e6f7ff",
        "custom-info-2": "#11acfa",
        "custom-indigo-1": "#faf0fa",
        "custom-indigo-2": "#ca6acc",
        "custom-indigo-3": "#3661ff",
        "custom-purple-1": "#5e7dbd",
        "custom-purple-2": "#a7b7db",
        "custom-purple-3": "#f3f6fb",
        "custom-grey-1": "#f7f7f7",
        "custom-grey-2": "#b1bcbd",
        "custom-grey-3": "#f2f5ff",
        "custom-grey-4": "#ededed",
        "custom-grey-5": "#fafafa",
        "custom-light-blue-1": "#c0e5f7",
        "custom-light-blue-2": "#2fabe0",
        "custom-light-yellow-1": "#fff4bf",
        "custom-light-green-1": "#e0f7dc",
        "custom-light-purple-1": "#ede4f5",
      },
      fontFamily: {
        "space-mono": ["SpaceMono", "sans-serif"],
        artegra: ["Artegra"],
        "artegra-bold": ["ArtegraBold"],
        "artegra-italic": ["ArtegraItalic"],
        "artegra-medium": ["ArtegraMedium"],
      },
    },
  },
  plugins: [],
};
